### PR TITLE
Molecule 2 Fixes

### PR DESCRIPTION
**Pull request by mplachter**
# Molecule 2 Fixes

* These changes are not backwards compatible with anything older then Ansible 2.4.0.0
* I would recommend creating a release on your current master branch and call it 1.0.
  * That release version will still allow users to pull it from `ansible-galaxy` to use if they have older versions of Ansible.

### CODE REVIEW

**Comment by popstas** [comment]
Thank you! I missed for replacing `volumes_mounts`...

I'm going to tag backwards commits also, I tag v1.0 when I begin using role in production, but usually I don't tagging forked roles for avoid conflicts with upstream. In this case upstream not maintained.

Also thanks for yamllint and verbose testinfra, I supressed it for time saving when migrate to molecule v2, now I have true v2 role :)

I merged PR, going to fix some more (min. ansible version, testinfra inventory lookup).
In next days I will rewrite kapacitor tasks definition method (with backward compatibility), will notify you.

**Comment by mplachter** [comment]
No problem. It was `volumes_mounts` as well as the **command** of `/sbin/init` needed to be passed. 

For the yamlint i made a config to excluded the line length rule and the parsing of the molecule folder.

I am following this role now, so when you make your additional changes i will know. :)

Thanks

**Comment by popstas** [comment]
@mplachter, molecule posted example of using systemd containers - https://molecule.readthedocs.io/en/latest/examples.html#systemd-container , our method too redundantly in access grant, i'll try to follow docs in next fixes.

**Comment by mplachter** [comment]
@popstas sounds good. I'll keep an eye out for your next push sir.

**Pull request merged**
